Added functionality to skip orphan removal if wished along with help text.

diff --git a/src/usr/bin/mumuh b/src/usr/bin/mumuh
--- a/src/usr/bin/mumuh
+++ b/src/usr/bin/mumuh
@@ -59,6 +59,8 @@ then
         printf '%s\n' "#        mumu --skipbackup                                           #"
         printf '%s\n' "#          OR                                                        #"
         printf '%s\n' "#        mumu -s                                                     #"
+        printf '%s\n' "#     * If you want to skip removing orphan pakackages:              #"
+        printf '%s\n' "#        mumu --skipOrphansRemove                                    #"
         printf '%s\n' "#     * If you want to use a custom command:                         #"
         printf '%s\n' "#        mumu --custombackupcommand=<custom command>                 #"
         printf '%s\n' "#          OR                                                        #"
@@ -116,6 +118,10 @@ then
                 else
                     CUSTOMBUCMD=$(echo "${CUSTOMBUARG}" | cut -f2 -d=)
                 fi
+                shift
+            ;;
+            --skipOrphansRemove)
+                SKIPORPHANRM=1
                 shift
             ;;
         esac
@@ -375,27 +381,29 @@ fi
 ###
 # START orphan cleaning section
 ###
-if [[ "${UPGRADE_OFFICIAL_RESULT}" -eq "0" ]] && [[ "${UPGRADE_AUR_RESULT}" -eq "0" ]] && [[ "${NEWMERGE_RESULT}" -eq "0" ]];
-then
-    if PAMAC_CLI_AUTH=1 pamac remove --orphans;
+if [ ${SKIPORPHANRM+x} ] && [[ "${SKIPORPHANRM}" -eq "1" ]]; then # $SKIPORPANRM variable not set and not equal to 1 (or true)
+    if [[ "${UPGRADE_OFFICIAL_RESULT}" -eq "0" ]] && [[ "${UPGRADE_AUR_RESULT}" -eq "0" ]] && [[ "${NEWMERGE_RESULT}" -eq "0" ]];
     then
-        if command -v notify-send 1> /dev/null 2> /dev/null;
+        if PAMAC_CLI_AUTH=1 pamac remove --orphans;
         then
-            notify-send --icon=checkmark --app-name="MUMUH" --expire-time=5000 "Successfully removed orphan packages."
+            if command -v notify-send 1> /dev/null 2> /dev/null;
+            then
+                notify-send --icon=checkmark --app-name="MUMUH" --expire-time=5000 "Successfully removed orphan packages."
+            else
+                printf "%sFailed to remove orphan packages.\n%sHuman intervention required.\nNot continuing.\n" "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[NORMAL}"
+            fi
         else
-            printf "%sFailed to remove orphan packages.\n%sHuman intervention required.\nNot continuing.\n" "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[NORMAL}"
+            if command -v notify-send 1> /dev/null 2> /dev/null;
+            then
+                notify-send --urgency=critical --icon=error --app-name="MUMUH" "Removing orphan packages" "\<br \/\>Using, pamac remove --orphans\<b\>\<\/b\>, failed."
+            else
+                printf "%sOrphan package removal, using %spamac remove --orphans%s failed.\n" "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[BOLD]}" "${TEXTFORMATTING[NORMAL}"
+            fi
         fi
     else
-        if command -v notify-send 1> /dev/null 2> /dev/null;
-        then
-            notify-send --urgency=critical --icon=error --app-name="MUMUH" "Removing orphan packages" "\<br \/\>Using, pamac remove --orphans\<b\>\<\/b\>, failed."
-        else
-            printf "%sOrphan package removal, using %spamac remove --orphans%s failed.\n" "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[BOLD]}" "${TEXTFORMATTING[NORMAL}"
-        fi
+        printf "%sOrphan packages could not be removed.\n%sHuman intervention required.\nNot continuing." "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[NORMAL}"
+        exit 13
     fi
-else
-    printf "%sOrphan packages could not be removed.\n%sHuman intervention required.\nNot continuing." "${TEXTFORMATTING[BRIGHT]}${TEXTFORMATTING[RED]}" "${TEXTFORMATTING[NORMAL}"
-    exit 13
 fi
 ###
 # END orphan cleaning section
